name: publish

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          path: skdassoc.com
      - uses: actions/setup-node@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun run build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: pages
  deploy:
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
